### ISSUE TITLE
Empty username

### ISSUE THREAD

**Issue by NicolaiRuckel** [jordanlewis/re#15]
I installed re with `go get github.com/jordanlewis/re` and created a Personal Access Token with repo scope and copied that to `$HOME/.github-issue-token` and ran

    chmod 600 ~/.github-issue-token
    git config --global github.user NicolaiRuckel

If I run `re` I don't get any output.

I can see PRs with `re -p user/project` but it doesn't show the "Created by me:" and "Involving me:" lines but just the PRs. For a specific PR I get the following output:

    2021/07/22 12:06:59 Fetching details for PR 100
    Username for 'https://github.com': 2021/07/22 12:06:59 Fetched issue comments in 306.136518ms
    2021/07/22 12:06:59 Fetched pr in 390.695837ms
    2021/07/22 12:06:59 Fetched reviews in 441.184566ms
    2021/07/22 12:07:00 Fetched review comments in 1.120997684s

This looks like my username is not read from my Git configuration. Do you have any ideas what the problem might be?

**Comment by jordanlewis** [comment]
You need to specify which GitHub repo to use with `-p`. I created this thing for my own work on https://github.com/cockroachdb/cockroach, so it defaults to that one :)

**Comment by NicolaiRuckel** [comment]
That's what I did. I tried it with a few of the repositories I'm involved with and I have the same problem with all of them.

**Comment by jordanlewis** [comment]
Hmm, okay, let me have a look. It's possible something has rotted. Thanks for trying out the project by the way!

**Comment by jordanlewis** [comment]
Are the repos that you're testing with private?

**Comment by jordanlewis** [comment]
I don't think that this project works properly with private repos. The code that fetches the refs uses `https://` style github repo urls instead of `git@` ones, which I think are required to work with private repos.

Do you have any public repos to test with to confirm my hypothesis?

Overall I'm realizing that the code probably should be restructured to use only GitHub API calls and not anything to do with the local `git` client, but I'm not sure when I'll have time to get to that.

In the mean time, you could try editing https://github.com/jordanlewis/re/blob/master/review.go#L112 to use the `git@github.com` style URL instead and see if that fixes things for you.

**Comment by NicolaiRuckel** [comment]
Yes, that was the problem. It works fine with public repositories as long as they have a branch named master.

I'll look into the changes you suggested when I have time, but I need to look into Go first, since I never did anything with that. :D

I really like the idea of the tool, though. Switching back and forth to the browser is really tedious, so I was happy to find an alternative to that (although it doesn't work for me at the moment).
